version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run: 
          name: Installing dependency
          command: go get ./...
      - run: 
          name: Running Test
          environment:
            MONGODB_URL: $MONGODB_URL
          command: go test -v
      - persist_to_workspace:
          root: .
          paths: .
      - store_test_results:
          path: results.json
workflows:
  testing-code:
    jobs:
      - test