version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.21.1
    environment:
      MONGODB_URL: $MONGODB_URL
    steps:
      - checkout
      - run: go mod tidy
      - run: go run .
      - run: go test
workflows:
  testing_code:
    jobs:
      - test