version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run: 
          name: Installing Dependencies
          command: go get ./...
      - run: 
          name: Making .env
          command: echo "MONGODB_URL=$MONGODB_URL" >> .env
      - run:
          name: Running Tests
          command: go test -v .
      - store_test_results:
          path: results.json
workflows:
  testing:
    jobs:
      - test