version: 2.1
orbs:
  go: circleci/go@1.8.0

jobs:
  test:
    executor:
      name: go/default
    steps:
      - checkout
      - go/load-cache
      - go/mod-download 
      - go/save-cache 
      - go/test:
          covermode: atomic
          failfast: true
          race: true
workflows:
  testing:
    jobs:
      - test