version: 2.1

jobs:
  test:
    docker:
      - image: cimg/go:1.21.1
    steps:
      - checkout
      - run: go mod download
      - run: 
          name: Downloading dependency
          environment:
            MONGODB_URL: MONGODB_URL
          command: go run .
      - run: 
          name: Running Test
          command: go test
      - store_test_results:
          path: results.json
workflows:
  testing-code:
    jobs:
      - test