name: Test

on: 
  push:
      branches:
          - main
  pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Install dependencies
        run: go get -v ./...

      - name: Test
        run: go test -v